services:
  besser-wme-frontend:
    build:
      context: ./besser/utilities/web_modeling_editor/BESSER-Web-Modeling-Editor
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${API_URL:-http://localhost:8000}
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:8000}
      - HUSKY=0
      - DISABLE_HUSKY=1
      - CI=true
    volumes:
      - /app/node_modules
    command: http-server dist -p 8080

  besser-wme-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app/besser
    environment:
      - PYTHONPATH=/app
    command: python -m besser.utilities.web_modeling_editor.backend.backend
